### ISSUE TITLE
Offsets committed for events being sent to index that doesn't exist

### ISSUE THREAD

**Issue by jamie00170** [splunk/kafka-connect-splunk#207]
The connector allows users to specify an index, source & sourcetype to send events to. If the index doesn't exist, Splunk still sends a 200 response back to the task which sent the batch of events. This means the task will commit the offsets for the events even though they weren't actually indexed. If possible we should have the HEC return a different status code and appropriate error message then mark the batch as failed. This would ensure that users are aware there is an issue with the configuration and offsets aren't committed meaning we can re-ingest those events again.

**Comment by ankit-splunk** [comment]
Hey @jamie00170,
when you do not provide any index in the connector config parameter then Splunk Hec ingests data into the default index. That's why Splunk sent a 200 response back to the tasks. So, no data loss happens here and it's working as expected. Also, you can provide the default index at the time of HEC creation.
I checked with below configuration, without using any index, source, sourcetype
```
curl localhost:8083/connectors -X POST -H "Content-Type: application/json" -d '{
 "name": "logging",
 "config": {
    "connector.class": "com.splunk.kafka.connect.SplunkSinkConnector",
    "tasks.max": "2",
    "topics":"test1",
    "splunk.indexes": "",
    "splunk.sources": "",
    "splunk.sourcetypes": "",
    "splunk.hec.uri": "http://10.202.15.129:8088",
    "splunk.hec.token": "00000000-0000-0000-0000-000000000000",
    "splunk.hec.raw": "true",
    "splunk.hec.raw.line.breaker": "\n",
    "splunk.hec.json.event.enrichment": "",
    "splunk.hec.ack.enabled": "false",
    "splunk.hec.ack.poll.interval": "10",
    "splunk.hec.ack.poll.threads": "2",
    "splunk.hec.ssl.validate.certs": "false",
    "splunk.hec.http.keepalive": "true",
    "splunk.hec.max.http.connection.per.channel": "4",
    "splunk.hec.total.channels": "2",
    "splunk.hec.max.batch.size": "1000",
    "splunk.hec.threads": "2",
    "splunk.hec.event.timeout": "60",
    "splunk.hec.socket.timeout": "120",
    "splunk.hec.track.data": "true",
    "splunk.hec.max.outstanding.events": "10000000"
   }
 }'
```
And data ingested on splunk via HEC successfully, attach screenshot below,
[
<img width="1550" alt="Screenshot 2022-01-13 at 3 30 23 PM" src="https://user-images.githubusercontent.com/89519839/149308631-9c51cc39-9a05-4f13-b2ef-a89c49153f0c.png">
](url)

**Comment by ankit-splunk** [comment]
@jamie00170, Closing the issue. If you are still facing the issue, feel free to reopen this or create a new one.
