### ISSUE TITLE
re-opening issue #268

### ISSUE THREAD

**Issue by amirofmn** [splunk/kafka-connect-splunk#281]
#268 

This feels like a bug to me.  The behavior we are observing doesn't seem to line-up with documentation.  The expected behavior would be the offsets writing to the topic we specify within our connect-distributed.properties file.  Not the connector default to __consumer_offsets

**Comment by hinchliff** [comment]
#133 seems related.  i don't see where the code for the configuration was removed, but it looks like the guidance was updated to use the default topics, and not custom topics?

**Comment by foram-splunk** [comment]
hi @amirofmn  , thanks for reaching out. I have looked into the issue and here is my analysis:

The issue you mentioned is related to offset.storage.topic, where connector offsets are stored.The offsets are committing to __consumer_offsets ,instead of topic mentioned in connect-distributed.properties file , as well as metadata is received for __consumer_offsets but not for __kafka-connect-splunk-offsets.

Kafka Connect uses the connect-offsets topic to store the offsets for source connectors, but sink connector offsets are stored using the normal Kafka consumer group mechanism. By default offsets are stored in __consumer_offsets.On going through the code , offsets are managed or configured through kafka and not modified/configured on kafka-connect-splunk.

We conclude that the Kafka connect framework itself manages and configures the offsets (to store them in default internal topics etc.) and kafka-splunk-connect does not change anything related to committing offset metadata. So I think this should be raised/discussed in Kafka Connect community instead.

Below are references for discussions related to similar issues:
https://stackoverflow.com/questions/41492347/kafka-connect-offset-storage-topic-not-receiving-messages-i-e-how-to-access-ka

https://stackoverflow.com/questions/35096321/kafka-offsets-information-not-available

https://stackoverflow.com/questions/42072854/kafka-connect-sink-task-ignores-file-offset-storage-property

**Comment by amirofmn** [comment]
@foram-splunk , thanks for the response and references on this issue.  I also came across a small thread on slack eluding to the same thing although I've yet to come across documentation that make the difference between source & sink connectors clearer in respects to where it stores it's offsets.  With that said, sounds like there's no actual issue with Splunk's sink connector and it's leveraging the kafka connect framework correctly.

**Comment by amirofmn** [comment]
Closing the issue. :)
